upstream backend_app {
    server 10.10.10.10:8080;
}

upstream hop_nginx3 {
    server 10.10.10.13:80;
}

server {
    listen 80;
    server_name nginx2;

    location = /health {
        default_type text/plain;
        return 200 "nginx2\n";
    }

    location / {
        include /etc/nginx/common/proxy_params.conf;
        proxy_pass http://backend_app;
    }

    location /chain/to-app/ {
        include /etc/nginx/common/proxy_params.conf;
        proxy_pass http://backend_app/;
    }

    location /chain/nginx3/ {
        include /etc/nginx/common/proxy_params.conf;
        proxy_pass http://hop_nginx3/chain/to-app/;
    }
}
