upstream backend_app {
    server 10.10.10.10:8080;
}

server {
    listen 80;
    server_name nginx3;

    location = /health {
        default_type text/plain;
        return 200 "nginx3\n";
    }

    location / {
        include /etc/nginx/common/proxy_params.conf;
        proxy_pass http://backend_app;
    }

    location /chain/to-app/ {
        include /etc/nginx/common/proxy_params.conf;
        proxy_pass http://backend_app/;
    }
}
