upstream backend_app {
    server 10.10.10.10:8080;
}

upstream hop_nginx2 {
    server 10.10.10.12:80;
}

upstream hop_nginx3 {
    server 10.10.10.13:80;
}

server {
    listen 80;
    server_name nginx1;

    location = /health {
        default_type text/plain;
        return 200 "nginx1\n";
    }

    # Прямой вход: пользователь → nginx1 → приложение
    location / {
        include /etc/nginx/common/proxy_params.conf;
        proxy_pass http://backend_app;
    }

    # Цепочка: nginx1 → nginx2 → приложение
    location /chain/nginx2/ {
        include /etc/nginx/common/proxy_params.conf;
        proxy_pass http://hop_nginx2/chain/to-app/;
    }

    # Цепочка: nginx1 → nginx3 → приложение
    location /chain/nginx3/ {
        include /etc/nginx/common/proxy_params.conf;
        proxy_pass http://hop_nginx3/chain/to-app/;
    }

    # Цепочка: nginx1 → nginx2 → nginx3 → приложение
    location /chain/nginx2/nginx3/ {
        include /etc/nginx/common/proxy_params.conf;
        proxy_pass http://hop_nginx2/chain/nginx3/;
    }
}
